require "webrick"
require "hanoi/webrick"
require "hanoi/browser"
require "hanoi/browsers/firefox"
require "hanoi/browsers/internet_explorer"
require "hanoi/browsers/konqueror"
require "hanoi/browsers/safari"
require "hanoi/browsers/opera"
